version: "3.9"

services:
  api:
    image: customerapi
    build: .
    pull_policy: always
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - mysql
    networks:
      - customer-network
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=customer_user
      - MYSQL_DATABASE=customer_db
    networks:
      - customer-network
    pull_policy: always
networks:
  customer-network:
    driver: bridge
