version: "3.9"

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=customers
      - MYSQL_ROOT_PASSWORD=passwor
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuserpassword
    networks:
      - customer-network
    pull_policy: always
  api:
    image: customerapi
    build: .
    pull_policy: always
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - customer-network
networks:
  customer-network:
    driver: bridge
volumes:
  mysqldata:
